name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

# These permissions are needed for deploying to GCP.
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    environment: 
      name: production
      url: https://celest.dev
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Git Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # 4.1.1
      - name: Setup pnpm
        uses: pnpm/action-setup@d2613e087f2e0aa841925861c5a5f7395d552177 # master
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # 4.0.0
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Install packages
        run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - name: Run build
        run: pnpm run build
      - name: GCP Auth
        id: gcp-auth
        uses: google-github-actions/auth@55bd3a7c6e2ae7cf1877fd1ccb9d54c0503c457c # 2.1.2
        with:
          workload_identity_provider: ${{ secrets.GCP_BUILD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_WEBSITE_SA }}
      - name: Upload Website
        uses: google-github-actions/upload-cloud-storage@22121cd842b0d185e042e28d969925b538c33d77 # 2.1.0
        with:
          path: build
          destination: ${{ secrets.GCP_WEBSITE_BUCKET }}
          parent: false # Upload to bucket root
          process_gcloudignore: false
